#PREREQUISITES
- name: install required packages
  apt: 
    name: [letsencrypt]
    update_cache: yes

- name: mkdir
  file: 
    dest: /var/encryptor 
    state: directory 
    mode: 0777
    
- name: create certificate
  command: letsencrypt certonly --webroot -w /var/encryptor -d {{ siteurl }} --agree-tos -m iponomarev@mail.ru
  args:
    creates: /etc/letsencrypt/live/{{ siteurl }}
  
- name: setup cert autoupdate
  cron:
    name: cert autoupdate
    weekday: 0
    minute: 17
    hour: 21
    job: "letsencrypt renew"
