<?php

namespace Management\AdminBundle\Repository;

/**
 * AdvantageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
