<?php

namespace Management\AdminBundle\Repository;

/**
 * AdvantageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvantageRepository extends \Doctrine\ORM\EntityRepository
{
}
