<?php

namespace Management\AdminBundle\Repository;

/**
 * ClientTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
