<?php

namespace Management\AdminBundle\Repository;

/**
 * CommonInformationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonInformationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
