<?php

namespace Management\AdminBundle\Repository;

/**
 * CommonInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommonInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
