<?php

namespace Management\AdminBundle\Repository;

/**
 * CompanyInformationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyInformationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
