<?php

namespace Management\AdminBundle\Repository;

/**
 * CompanyInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
