<?php

namespace Management\AdminBundle\Repository;

/**
 * ComponentTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
