<?php

namespace Management\AdminBundle\Repository;

/**
 * FeedSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
