<?php

namespace Management\AdminBundle\Repository;

/**
 * FeedStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
