<?php

namespace Management\AdminBundle\Repository;

/**
 * SourceLinkTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceLinkTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
