<?php

namespace Management\AdminBundle\Repository;

/**
 * SourceLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
