<?php

namespace Management\AdminBundle\Repository;

/**
 * TextTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
