<?php

namespace Management\AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
    public function findAdminAccount() {

        return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('u')
                ->from('ManagementAdminBundle:User', 'u')
                ->where('u.roles LIKE :role')
                ->setParameter('role', '%ROLE_ADMIN%')
                ->getQuery()
//                ->getSingleScalarResult()
                ->getOneOrNullResult()
            ;
    }
}
