<?php

namespace Management\AdminBundle\Repository;

/**
 * VersionLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionLinksRepository extends \Doctrine\ORM\EntityRepository
{
}
