<?php

namespace Translation\LocaleBundle\Repository;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends \Doctrine\ORM\EntityRepository
{
}
