management_admin_common_information:
    resource: "@ManagementAdminBundle/Controller/CommonInformationController.php"
    type:     annotation

management_admin_client:
    resource: "@ManagementAdminBundle/Controller/ClientController.php"
    type:     annotation

management_admin_advantage:
    resource: "@ManagementAdminBundle/Controller/AdvantageController.php"
    type:     annotation

management_admin_component:
    resource: "@ManagementAdminBundle/Controller/ComponentController.php"
    type:     annotation

management_admin_security:
    resource: "@ManagementAdminBundle/Controller/SecurityController.php"
    type:     annotation
#    prefix:   /

management_admin_main:
    resource: "@ManagementAdminBundle/Controller/MainController.php"
    type:     annotation

initial:
    resource: "@ManagementAdminBundle/Controller/InitialController.php"
    type:     annotation

frontend_components:
    resource: "@FrontendComponentsBundle/Controller/"
    type:     annotation
    prefix:   /