management_admin_security:
    resource: "@ManagementAdminBundle/Controller/SecurityController.php"
    type:     annotation
#    prefix:   /

management_admin_main:
    resource: "@ManagementAdminBundle/Controller/MainController.php"
    type:     annotation

initial:
    resource: "@ManagementAdminBundle/Controller/InitialController.php"
    type:     annotation

frontend_components:
    resource: "@FrontendComponentsBundle/Controller/"
    type:     annotation
    prefix:   /