management_admin_feed_status:
    resource: "@ManagementAdminBundle/Controller/FeedStatusController.php"
    type:     annotation

management_admin_feed_source:
    resource: "@ManagementAdminBundle/Controller/FeedSourceController.php"
    type:     annotation

management_admin_feed:
    resource: "@ManagementAdminBundle/Controller/FeedController.php"
    type:     annotation

management_admin_feeds:
    resource: "@ManagementAdminBundle/Controller/FeedsController.php"
    type:     annotation

rssatom:
    resource: "@DebrilRssAtomBundle/Resources/config/routing.yml"

management_admin_company_information:
    resource: "@ManagementAdminBundle/Controller/CompanyInformationController.php"
    type:     annotation

management_admin_common_information:
    resource: "@ManagementAdminBundle/Controller/CommonInformationController.php"
    type:     annotation

management_admin_client:
    resource: "@ManagementAdminBundle/Controller/ClientController.php"
    type:     annotation

management_admin_advantage:
    resource: "@ManagementAdminBundle/Controller/AdvantageController.php"
    type:     annotation

management_admin_component:
    resource: "@ManagementAdminBundle/Controller/ComponentController.php"
    type:     annotation

management_admin_security:
    resource: "@ManagementAdminBundle/Controller/SecurityController.php"
    type:     annotation
#    prefix:   /

management_admin_main:
    resource: "@ManagementAdminBundle/Controller/MainController.php"
    type:     annotation

initial:
    resource: "@ManagementAdminBundle/Controller/InitialController.php"
    type:     annotation

frontend_components:
    resource: "@FrontendComponentsBundle/Controller/"
    type:     annotation
    prefix:   /