# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /admin

    encoders:
        Management\AdminBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin_provider:
            entity:
                class: Management\AdminBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
#        main:
            pattern: ^/
#            anonymous: ~
            anonymous:    true
            form_login:
                provider: admin_provider
#                csrf_token_generator: security.csrf.token_manager

                # the user is redirected here when they need to log in
                login_path: /admin

                # submit the login form here
                check_path: /admin/login_check

                # if true, forward the user to the login form instead of redirecting
                use_forward: false

                # field names for the username and password fields
                username_parameter: _username
                password_parameter: _password

                # login success redirecting options
                success_handler: login_success_handler

                # login success redirecting options
                always_use_default_target_path: false
                default_target_path: /
                use_referer: false
#            logout: true
            logout:
                path:   /admin/logout
                target: /admin

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
#        - { path: ^/(login)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/(register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }