nginx_user: "www-data"
nginx_sites:
  encryptor:
    - listen 80
    - server_name encryptor
    - location ~ /.well-known {root "/var/encryptor"; allow all; }
    - location / { rewrite ^/(.*)$ https://$host/$1 permanent; }
    
php_packages:
  - php7.0
  - php7.0-bcmath
  - php7.0-cgi
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-fpm
  - php7.0-gd
  - php7.0-intl
  - php7.0-json
  - php7.0-mbstring
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-pgsql
  - php7.0-readline
  - php7.0-xml
php_webserver_daemon: "nginx"
  
mysql_root_username: "{{ mysqluser }}"
mysql_root_password: "{{ mysqlpwd }}"
mysql_databases: 
  - name: wikidb

postgresql_databases:
  - name: corchestra
postgresql_users:
  - name: "{{ postgreuser }}"
    password: "{{ postgrespwd }}"