Management\AdminBundle\Entity\Advantage:

    type: entity

    table: advantage

    repositoryClass: Management\AdminBundle\Repository\AdvantageRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        imageName:        { type: string, length: 255, nullable: true }
        description:      { type: text, nullable: true }

        dateOfCreation:   { type: datetime, nullable: false }
        dateOfChange:     { type: datetime, nullable: false }

    manyToOne: { }

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }