Management\AdminBundle\Entity\ClientTranslation:

    type: entity

    table: client_translation

    repositoryClass: Management\AdminBundle\Repository\ClientTranslationRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:              { type: text, nullable: true }
        colorImageName:     { type: string, length: 255, nullable: true }

        dateOfCreation:     { type: datetime, nullable: false }
        dateOfChange:       { type: datetime, nullable: false }

    manyToOne:
        source:
            targetEntity: Management\AdminBundle\Entity\Client
            inversedBy: translations
            joinColumn:
                name: source_id
                referencedColumnName: id
        locale:
            targetEntity: Translation\LocaleBundle\Entity\Locale
            joinColumn:
                name: locale_id
                referencedColumnName: id

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }