Management\AdminBundle\Entity\Client:

    type: entity

    table: client

    repositoryClass: Management\AdminBundle\Repository\ClientRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        colorImageName:     { type: string, length: 255, nullable: true }

        dateOfCreation:     { type: datetime, nullable: false }
        dateOfChange:       { type: datetime, nullable: false }

    manyToOne: { }

    oneToOne: { }

    oneToMany:
        translations:
            targetEntity: Management\AdminBundle\Entity\ClientTranslation
            mappedBy: source

    manyToMany: { }

lifecycleCallbacks: { }