Management\AdminBundle\Entity\ComponentTranslation:

    type: entity

    table: component_translation

    repositoryClass: Management\AdminBundle\Repository\ComponentTranslationRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:             { type: string, length: 128, nullable: true }
        description:      { type: text, nullable: true }

        dateOfCreation:   { type: datetime, nullable: false }
        dateOfChange:     { type: datetime, nullable: false }

    manyToOne:
        source:
            targetEntity: Management\AdminBundle\Entity\Component
            inversedBy: translations
            joinColumn:
                name: source_id
                referencedColumnName: id
        locale:
            targetEntity: Translation\LocaleBundle\Entity\Locale
            joinColumn:
                name: locale_id
                referencedColumnName: id

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }