Management\AdminBundle\Entity\Component:

    type: entity

    table: component

    repositoryClass: Management\AdminBundle\Repository\ComponentRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:             { type: string, length: 128, nullable: true }
        description:      { type: text, nullable: true }
        wikiUrl:          { type: string, length: 256, nullable: true }

        dateOfCreation:   { type: datetime, nullable: false }
        dateOfChange:     { type: datetime, nullable: false }

    manyToOne: { }

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }