Management\AdminBundle\Entity\SourceTranslation:

    type: entity

    table: source_translation

    repositoryClass: Management\AdminBundle\Repository\SourceTranslationRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:            { type: string, length: 64, nullable: true }
        subtitle:         { type: string, length: 128, nullable: true }

        dateOfCreation:   { type: datetime, nullable: false }
        dateOfChange:     { type: datetime, nullable: false }

    manyToOne:
        source:
            targetEntity: Management\AdminBundle\Entity\Source
            inversedBy: translations
            joinColumn:
                name: source_id
                referencedColumnName: id
        locale:
            targetEntity: Translation\LocaleBundle\Entity\Locale
            joinColumn:
                name: locale_id
                referencedColumnName: id

    oneToOne: { }

    oneToMany:
        sourceLinkTranslations:
            targetEntity: Management\AdminBundle\Entity\SourceLinkTranslation
            mappedBy: sourceTranslation
            cascade: ["persist", "remove"]

    manyToMany: { }

lifecycleCallbacks: { }