Management\AdminBundle\Entity\Subscriber:

    type: entity

    table: subscriber

    repositoryClass: Management\AdminBundle\Repository\SubscriberRepository

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        email:                      { type: string, length: 128, nullable: true }
        subscribedToFeed:           { type: boolean, nullable: true }

        dateOfCreation:             { type: datetime, nullable: false }
        dateOfChange:               { type: datetime, nullable: false }

    manyToOne: { }

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }