Management\AdminBundle\Entity\TextTranslation:

    type: entity

    table: text_translation

    repositoryClass: Management\AdminBundle\Repository\TextTranslationRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        text:             { type: string, length: 1024, nullable: true }

        dateOfCreation:   { type: datetime, nullable: false }
        dateOfChange:     { type: datetime, nullable: false }

    manyToOne:
        source:
            targetEntity: Management\AdminBundle\Entity\Text
            inversedBy: translations
            joinColumn:
                name: source_id
                referencedColumnName: id
        locale:
            targetEntity: Translation\LocaleBundle\Entity\Locale
            joinColumn:
                name: locale_id
                referencedColumnName: id

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }