Management\AdminBundle\Entity\User:

    type: entity

    table: system_user

    repositoryClass: Management\AdminBundle\Repository\UserRepository

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        username:                   { type: string, length: 128, nullable: true }
        usernameCanonical:          { column: username_canonical, type: string, length: 128, nullable: true }
        email:                      { type: string, length: 128, nullable: true }
        emailCanonical:             { column: email_canonical, type: string, length: 128, nullable: true }
        enabled:                    { type: boolean, nullable: true }
        salt:                       { type: string, length: 255, nullable: true }
        password:                   { type: string, length: 255, nullable: true }
        lastLogin:                  { type: datetime, nullable: true }
        roles:                      { type: array, nullable: true }

        dateOfCreation:             { type: datetime, nullable: false }
        dateOfChange:               { type: datetime, nullable: false }

    manyToOne: { }

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }