Management\AdminBundle\Entity\VersionLinks:

    type: entity

    table: version_links

    repositoryClass: Management\AdminBundle\Repository\VersionLinksRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        linkType:         { type: string, length: 128, nullable: false }
        linkUrl:          { type: string, length: 256, nullable: false }


    manyToOne: { }

    oneToOne: { }

    oneToMany: { }

    manyToMany: { }

lifecycleCallbacks: { }