- name: configure platfrom website server
  hosts: website
  vars:
    siteurl: "corchestra.ru"
  vars_files:
    - vars/webserver.yml
  roles:
    - role: jdauphant.nginx
    - role: letsencrypt
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: geerlingguy.mysql
    - role: mediawiki
    - role: geerlingguy.postgresql
    - role: webpage
    - role: sftp
    - role: svnsync